Update versioning.mdx
mintlify/docs pull request #296
Opened 2024-10-11 22:10 UTC by dino475

editing the versions documentation to reflect the new feature mentioned here: https://app.plain.com/workspace/w_01H3FZJ8MG74GFXA5WA3MPB446/thread/th_01J8072V8GHJ17KYP2B1SNHGJX/

2024-10-11 22:13 UTC, mxbaylee requested changes

2024-10-11 22:13 UTC, mxbaylee commented on settings/versioning.mdx
> +}
```suggestion
  {
    "name": "version-name",
    "default": true
  }
```

2024-10-11 22:13 UTC, mxbaylee commented on settings/versioning.mdx
> +}
json needs keys to be quoted, and the indention since it's changin' already [:

2024-12-19 20:04 UTC, rpmccarter approved these changes

2024-12-19 20:05 UTC, merged