Feedback config in Global Settings page
mintlify/docs pull request #85
Opened 2023-07-27 06:17 UTC by eugenechantk

I added some explanations to toggle the feedback section + repo in the global settings page

2023-07-27 16:42 UTC, rpmccarter requested changes

2023-07-27 16:42 UTC, rpmccarter commented on settings/global.mdx
> +
This is a little confusing, but repo isn't actually configured in the mint.json. It's configured somewhere else, not exactly sure where though

2023-07-27 16:42 UTC, rpmccarter commented on settings/global.mdx
> +</ResponseField>
This section already exists, see line 263, just add to that section

2024-10-22 21:37 UTC, hahnbeelee commented
closing cuz outdated

2024-10-22 21:37 UTC, closed without merging